spring.application.name=lab7_673380585_0_sec3

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/lab7demo
spring.datasource.username=postgres
spring.datasource.password=p123

# JPA / Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false